version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/ena_open
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 120
  ApplicationStart:
    - location: scripts/reload.sh
      timeout: 60